theme: jekyll-theme-minimal
title: Yannick KREMPP
description: Scripts and docs in Python, Image J and more for the scientific community.
linkedin: /in/yannick-krempp
github: /universalbuilder
google_analytics: UA-160728201-1
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
